theme: jekyll-theme-architect

header_pages:
  - _pages/links.md

lsi: false
safe: true
source: [/]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge